// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using XHomes.Data;

namespace XHomes.Migrations.Estimate
{
    [DbContext(typeof(EstimateContext))]
    [Migration("20210619202659_EstimateInitialMigration4")]
    partial class EstimateInitialMigration4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("XHomes.Models.Estimate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("city")
                        .HasColumnType("text");

                    b.Property<int>("condition")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("email")
                        .HasColumnType("text");

                    b.Property<string>("fileName")
                        .HasColumnType("text");

                    b.Property<string>("filePath")
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<string>("jobType")
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<string>("matDescription")
                        .HasColumnType("text");

                    b.Property<string>("phone")
                        .HasColumnType("text");

                    b.Property<string>("state")
                        .HasColumnType("text");

                    b.Property<string>("workDescription")
                        .HasColumnType("text");

                    b.Property<string>("zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estimate");
                });

            modelBuilder.Entity("XHomes.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EstimateId")
                        .HasColumnType("integer");

                    b.Property<string>("matDescription")
                        .HasColumnType("text");

                    b.Property<string>("material")
                        .HasColumnType("text");

                    b.Property<string>("price")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstimateId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("XHomes.Models.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("EstimateId")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<int>("priority")
                        .HasColumnType("integer");

                    b.Property<string>("title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstimateId");

                    b.ToTable("WorkTask");
                });

            modelBuilder.Entity("XHomes.Models.Material", b =>
                {
                    b.HasOne("XHomes.Models.Estimate", null)
                        .WithMany("materials")
                        .HasForeignKey("EstimateId");
                });

            modelBuilder.Entity("XHomes.Models.WorkTask", b =>
                {
                    b.HasOne("XHomes.Models.Estimate", null)
                        .WithMany("tasks")
                        .HasForeignKey("EstimateId");
                });

            modelBuilder.Entity("XHomes.Models.Estimate", b =>
                {
                    b.Navigation("materials");

                    b.Navigation("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
